owner: maximousblk
repo: status

user-agent: maximousblk

sites:
  - name: Google
    url: https://www.google.com
    icon: https://www.google.com/favicon.ico
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  name: Status Page

  baseUrl: /status
  logoUrl: https://github.com/maximousblk.png
  themeUrl: https://example.com/my-custom-theme.css

  favicon: https://github.com/maximousblk.png

  introTitle: "This is a test status page using Upptime"
  introMessage: This is a sample status page. No server required — just GitHub Actions, Issues, and Pages.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
