owner: maximousblk
repo: status

user-agent: maximousblk

sites:
  - name: Google
    url: https://www.google.com
    icon: https://www.google.com/favicon.ico

  - name: Maximous Black
    url: https://maximousblk.me
    icon: https://maximousblk.me/favicon.ico

  - name: Nest Land
    url: https://nest.land
    icon: https://docs.nest.land/img/logo.svg

  - name: Deno
    url: https://deno.land
    icon: https://deno.land/favicon.ico

  - name: Test Broken Site
    url: this.site.does.not.exist

status-website:
  name: Status Page

  baseUrl: /status
  logoUrl: https://github.com/maximousblk.png
  themeUrl: https://cdn.maximousblk.now.sh/css/nest-status-theme.css

  favicon: https://github.com/maximousblk.png

  introTitle: "This is a test status page using Upptime"
  introMessage: This is a sample status page. No server required — just GitHub Actions, Issues, and Pages.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
